<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '8d64e7f950b5a1fa0e4673a4687539f7',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/sf55?serverVersion=5.7',
);
