<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCjahud2\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCjahud2/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerCjahud2.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerCjahud2\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerCjahud2\App_KernelProdContainer([
    'container.build_hash' => 'Cjahud2',
    'container.build_id' => 'bc14f686',
    'container.build_time' => 1575895447,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCjahud2');
